### ISSUE TITLE
Images in readme.md

### ISSUE THREAD

**Issue by Peter554** [NiklasRosenstein/pydoc-markdown#32] opened 2018-02-10 23:45 UTC
So when I add images to the readme.md with e.g. 

`<img src='demo/Tumor_004_thumb.png' width='20%'/>`

they are correctly rendered on the repo github page. However, in the generated docs the links/images seem to broken? Is this a feature we can fix/add?

**Comment by NiklasRosenstein** [comment] 2018-02-15 12:16
This is definitely something that should be fixed, or rather added as a feature as it can hardly be a bug when there is no code to handle the case. 😃

**Comment by sverch** [comment] 2018-09-10 15:36
I ran into a similar issue.  Part of the problem is that I wasn't sure how to get pydocmd to copy the images in since it only copies markdown files from `docs_dir`.  So I made https://github.com/NiklasRosenstein/pydoc-markdown/pull/56 to copy all files from `docs_dir`.  With that you can symlink any images into that directory that you want pydocmd to copy and it seems like it works.

**Comment by NiklasRosenstein** [comment] 2020-03-01 15:30
Closing in favor of #94

**Closed by NiklasRosenstein** 2020-03-01 15:30 UTC
Labels: feature request, good first issue
