### ISSUE TITLE
Module without module-level docstrings fails

### ISSUE THREAD

**Issue by AuHau** [NiklasRosenstein/pydoc-markdown#67] opened 2018-12-03 04:52 UTC
With current develop branch, if I am trying to generate docs from file which does not have module-level (eq. first thing) docstring, the execution fails with:

```
Traceback (most recent call last):
  File "/Users/c5272397/dev/toggl-cli/.direnv/python-3.6.5/bin/pydoc-markdown", line 11, in <module>
    sys.exit(_entry_point())
  File "/Users/c5272397/dev/toggl-cli/.direnv/python-3.6.5/lib/python3.6/site-packages/pydoc_markdown/__main__.py", line 25, in <lambda>
    _entry_point = lambda: sys.exit(main())
  File "/Users/c5272397/dev/toggl-cli/.direnv/python-3.6.5/lib/python3.6/site-packages/pydoc_markdown/__main__.py", line 19, in main
    module = parse_file(fp.read(), args.filename)
  File "/Users/c5272397/dev/toggl-cli/.direnv/python-3.6.5/lib/python3.6/site-packages/pydoc_markdown/parsing/parser.py", line 26, in parse_file
    return Parser().parse(parse_to_ast(code, filename), filename, module_name)
  File "/Users/c5272397/dev/toggl-cli/.direnv/python-3.6.5/lib/python3.6/site-packages/pydoc_markdown/parsing/parser.py", line 40, in parse
    docstring = self.get_docstring_from_first_node(ast, module_level=True)
  File "/Users/c5272397/dev/toggl-cli/.direnv/python-3.6.5/lib/python3.6/site-packages/pydoc_markdown/parsing/parser.py", line 232, in get_docstring_from_first_node
    return self.get_hashtag_docstring_from_prefix(node)
  File "/Users/c5272397/dev/toggl-cli/.direnv/python-3.6.5/lib/python3.6/site-packages/pydoc_markdown/parsing/parser.py", line 242, in get_hashtag_docstring_from_prefix
    prefix = self.get_most_recent_prefix(node)
  File "/Users/c5272397/dev/toggl-cli/.direnv/python-3.6.5/lib/python3.6/site-packages/pydoc_markdown/parsing/parser.py", line 216, in get_most_recent_prefix
    while not node.prev_sibling and not node.prefix:
AttributeError: 'NoneType' object has no attribute 'prev_sibling'
```

Example code which fails:
```python
def some_fnc(arg):
    """
    Doc string
    :param arg:
    :return:
    """
    pass


class A:
    """
    Some class!
    """

    # Attr 1
    attr1 = 'asd'
```

**Comment by NiklasRosenstein** [comment] 2020-03-01 04:08
Hey I think this was with an old state on the develop branch? I can't reproduce this issue anymore, so going to close it out.

```
$ cat <'EOF' >a.py
def some_fnc(arg):
    """
    Doc string
    :param arg:
    :return:
    """
    pass


class A:
    """
    Some class!
    """

    # Attr 1
    attr1 = 'asd'
EOF
$ pydoc-markdown --modules a --search-path .
```

---

# Table of Contents

* [a](#a)
  * [some\_fnc](#a.some_fnc)
  * [A](#a.A)
    * [attr1](#a.A.attr1)

<a name="a"></a>
# `a`

<a name="a.some_fnc"></a>
## `some_fnc()`

```python
def some_fnc(arg)
```

Doc string
:param arg:
:return:

<a name="a.A"></a>
## `A` Objects

```python
class A()
```

Some class!

<a name="a.A.attr1"></a>
### `attr1`

**Closed by NiklasRosenstein** 2020-03-01 04:08 UTC
Labels: bug
